// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type LoginClientInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginClientOutput struct {
	AccessToken string `json:"accessToken"`
}

type Mutation struct {
}

type NewUserClient struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type Query struct {
}

type User struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Email     string     `json:"email"`
	Phone     string     `json:"phone"`
	Status    string     `json:"status"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
}
